version: '3.8'
services:
  sample-backend:
    build:
      dockerfile: /backend.Dockerfile
    volumes:
      - sqlite-data:/app/db
    env_file: 
      - local.env

volumes:
  sqlite-data: